[customizations]

[[customizations.user]]
name = "tuonome"
password = "tuapassword"
groups = ["wheel"]

[customizations.installer.kickstart]
contents = """
ostreecontainer --url ghcr.io/Th3Modder/Bazzite-Lite:latest --no-signature-verification
"""
